### ISSUE TITLE
[BUG] Eccezione al ripristino delle impostazioni

### ISSUE THREAD

**Issue by mikyll** [mikyll/ROQuiz#18]
**Descrivi il bug**
Quando si ripristinano le impostazioni, mentre c'è un'animazione in corso, l'app spara un'eccezione (non dà problemi in Release, solo in debug).

**Come riprodurre**
Passaggi per riprodurre il bug:
1. Avviare l'app in **debug mode**;
2. Vai nella pagina delle Impostazioni (ViewSettings);
3. Partendo dalle impostazioni di default;
4. Deseleziona gli alert di conferma;
5. Imposta il tema scuro;
6. Ripristina le impostazioni;
7. Eccezione sparata dall'AnimationController

**Comportamento previsto**
Nessuna eccezione.

**Screenshot**
-

**Desktop:**
 - SO: Windows
 - Versione: 1.10.0

**Informazioni aggiuntive**
Debug output:
```lang-none
════════ Exception caught by animation library ═════════════════════════════════
The following assertion was thrown while notifying status listeners for AnimationController:
'package:flutter/src/widgets/overlay.dart': Failed assertion: line 1392 pos 14: '_zOrderIndex != null': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.yml

When the exception was thrown, this was the stack:
#2      OverlayPortalController.hide (package:flutter/src/widgets/overlay.dart:1392:14)
overlay.dart:1392
#3      TooltipState._handleStatusChanged (package:flutter/src/material/tooltip.dart:442:28)
tooltip.dart:442
#4      AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:240:19)
listener_helpers.dart:240
#5      AnimationController._checkStatusChanged (package:flutter/src/animation/animation_controller.dart:815:7)
animation_controller.dart:815
#6      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:831:5)
animation_controller.dart:831
#7      Ticker._tick (package:flutter/src/scheduler/ticker.dart:249:12)
ticker.dart:249
#8      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325:15)
binding.dart:1325
#9      SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1177:11)
binding.dart:1177
#10     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
compact_hash.dart:633
#11     SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1175:17)
binding.dart:1175
#12     SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:1092:5)
binding.dart:1092
#13     _invoke1 (dart:ui/hooks.dart:328:13)
hooks.dart:328
#14     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:351:5)
platform_dispatcher.dart:351
#15     _beginFrame (dart:ui/hooks.dart:272:31)
hooks.dart:272
(elided 2 frames from class _AssertionError)

The AnimationController notifying status listeners was: AnimationController#7eab8(⏮ 0.000; paused)
════════════════════════════════════════════════════════════════════════════════
```

**Comment by mikyll** [comment]
Probabilmente è causato dall'animazione delle checkbox: quando si clicca il bottone che ripristina le impostazioni, viene triggerato il restart dell'animazione, ma quella precedente (inversa) non è ancora terminata.
